### ISSUE TITLE
Award not reflected on people page

### ISSUE THREAD

**Issue by binaryberry** [rowanmanning/crossword#23]
As a binaryberry,
When I get a bronze award on 5th of October 2022: https://crossword.rowanmanning.com/leaderboards/2022-10-05/
Then I want to see the date updated on my people page: https://crossword.rowanmanning.com/people/binaryberry/#award-bronze

**Comment by rowanmanning** [comment]
I do see it listed [in the times table on your people page](https://crossword.rowanmanning.com/people/binaryberry/#times), and the Bronze award on that page now has a `x2` for me as well

**Comment by binaryberry** [comment]
ah ok thanks @rowanmanning ! I totally assumed it was the latest date you'd received the award as opposed to the first. 
Brains eh? Why can't they all think the same?
