### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by apaleslimghost** [rowanmanning/crossword#3]
Post to slack when a person's time for today is scraped

**Comment by rowanmanning** [comment]
Yeah I like this idea 👍  it _should_ be doable by diffing the data files. Alternatively it could post to Slack daily on a schedule, like towards the end of the day

**Comment by alexwilson** [comment]
Notifications throughout the day might be more annoying, but, might nudge more people to play.

**Comment by rowanmanning** [comment]
Realistically never gonna do this so gonna close
