### ISSUE TITLE
Award for being faster than Nick

### ISSUE THREAD

**Issue by alexwilson** [rowanmanning/crossword#5]
# Why?
When it's cold and rainy outside, and there's a tube strike on so you can't even go to the office, sometimes all you really need is a small win and a kind smile.

# What?
When you beat Nick's time, you should receive a badge - from @nickramsbottom - congratulating you on the win.

**Comment by nickramsbottom** [comment]
It would be fun to have an award for beating yesterday's winner if they have played that day
